# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('units', models.IntegerField(default=0)),
                ('desc', models.TextField()),
                ('coreqs', models.ManyToManyField(blank=True, null=True, related_name='classes_unlocked_coreq', to='api.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('building', models.CharField(blank=True, default='', max_length=50)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('days', models.CharField(blank=True, default='', max_length=50)),
                ('instructors', models.ManyToManyField(related_name='lectures', to='api.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_course', to='api.Meeting'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes_unlocked_prereq', to='api.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_course', to='api.Meeting'),
        ),
    ]
