# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
