# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161018_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
