# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161018_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='instructors',
        ),
    ]
