# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_meeting_instructors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='building',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='days',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
