# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161018_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lectures',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_course', to='api.Meeting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='sections',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='section_course', to='api.Meeting'),
            preserve_default=False,
        ),
    ]
