# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161018_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
        migrations.AddField(
            model_name='meeting',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='api.Course'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
