# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161018_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(related_name='classes_unlocked_coreq', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(related_name='classes_unlocked_prereq', to='api.Course'),
        ),
    ]
